version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn --frozen-lockfile --network-concurrency 1
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn lint
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn --frozen-lockfile --network-concurrency 1
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn content
      - run: yarn generate
  deploy:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn --frozen-lockfile --network-concurrency 1
      - run: yarn content
      - run: yarn generate
      - run: yarn -s deploy --token="$FIREBASE_TOKEN" --project="$FIREBASE_PROJECT_ID"
workflows:
  version: 2
  build-deploy:
    jobs:
      - lint:
          filters:
            branches:
              only: master
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - lint
            - build
          filters:
            branches:
              only: master
